[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_message_board = "AEtjhvM2nkjjrvQF1K2xcPV9mERpbjqrZEvgKavmbuaR"

[programs.devnet]
solana_message_board = "CTo9zyKZRzHmQT7TvogQ6r8Z7AMd8asTf8AMyBAJFcUj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/"

[test]
startup_wait = 10000   # wait 10 seconds instead of default 5


